# listen
ApiListen = "localhost:6065"

#batchUpload max num of keys once upload
MaxNum = 16

# enable golang pprof
PprofEnable = true

# pprof http addr
PprofListen = "localhost:6066"

# max file size
MaxFileSize = 41943040

[snowflake]
# zookeeper cluster addrs, multiple addrs split by ",".
ZkAddrs = [
    "10.10.191.8:2183"
]

# path
ZkPath = "/gosnowflake-servers"

# timeout
ZkTimeout = "15s"

# workid
WorkId = 0

[zookeeper]
# zookeeper cluster addrs, multiple addrs split by ",".
Addrs = [
    "10.10.191.8:2183"
]

# zookeeper heartbeat timeout.
Timeout = "15s"

# zookeeper storeroot path.
StoreRoot = "/rack"

# zookeeper volumeroot path
VolumeRoot = "/volume"

# zookeeper grouproot path
GroupRoot = "/group"

# zookeeper pullinterval
PullInterval = "10s"

# directoryroot node
DirectoryRoot = "/directory"

[hbase]
# addr 172.16.13.90:9090
Addr = "172.16.13.90:9090"

# Note that you must specify a number here.
MaxActive = 100

# Note that you must specify a number here.
MaxIdle = 100

# Note that you must specify a number here.
Timeout = "1s"

[redis]
# redis address
Addr = "10.10.191.7:8888"

# max idle connection in pool
MaxIdle = 100

# idle timeout (seconds)
Timeout = 240
