PprofEnable = true

PprofListen = "localhost:2231"

HttpAddr = "10.10.191.7:2232"

BfsAddr = "localhost:6065"

Domain = "http://10.10.191.7:2232/"                                                                              

Prefix = "/xfs/"

MaxFileSize = 20971520

PurgeMaxSize = 100000

[redis]
# redis address
Addr = "localhost:6379"

# max idle connection in pool
MaxIdle = 100

# idle timeout (seconds)
Timeout = 240
