PprofEnable = true

PprofListen = "localhost:2231"

HttpAddr = "10.10.191.7:2232"

Domain = "http://10.10.191.7:2232/"                                                                              

Prefix = "/xfs/"

MaxFileSize = 41943040

PurgeMaxSize = 100000

[zookeeper]
DirectoryRoot = "/directory"
Addr = ["10.10.191.8:2183"]
Timeout = 1
